INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (7, '权限管理', 8, 1, 100, 'fa fa-balance-scale', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (8, '系统菜单', null, 0, 200, '', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (9, '资源管理', 7, 1, 100, '', 'ResourceController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (12, '角色管理', 7, 1, 100, '', 'RoleController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (13, '用户管理', 7, 1, 100, '', 'BackendUserController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (14, '系统管理', 8, 1, 80, 'fa fa-gears', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (15, '激活码管理', 8, 1, 90, 'fa fa-gears', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (21, '业务菜单', null, 0, 170, '', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (22, '课程资源(空)', 21, 1, 100, 'fa fa-book', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (23, '日志管理(空)', 14, 1, 100, '', '');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (25, '编辑', 9, 2, 100, 'fa fa-pencil', 'ResourceController.Edit');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (26, '编辑', 13, 2, 100, 'fa fa-pencil', 'BackendUserController.Edit');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (27, '删除', 9, 2, 100, 'fa fa-trash', 'ResourceController.Delete');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (29, '删除', 13, 2, 100, 'fa fa-trash', 'BackendUserController.Delete');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (30, '编辑', 12, 2, 100, 'fa fa-pencil', 'RoleController.Edit');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (31, '删除', 12, 2, 100, 'fa fa-trash', 'RoleController.Delete');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (32, '分配资源', 12, 2, 100, 'fa fa-th', 'RoleController.Allocate');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (35, ' 首页', null, 1, 100, 'fa fa-dashboard', 'HomeController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (40, '激活码查询', 15, 1, 100, 'fa fa-pencil', 'ActivationCodeController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (41, '商户管理', 15, 1, 100, 'fa fa-pencil', 'PcMchtInfosController.Index');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (42, '编辑', 41, 2, 100, 'fa fa-pencil', 'PcMchtInfosController.Edit');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (43, '删除', 41, 2, 100, 'fa fa-pencil', 'PcMchtInfosController.Delete');
INSERT INTO tbl_resource (id, name, parent_id, rtype, seq, icon, url_for) VALUES (44, '编辑', 40, 2, 100, 'fa fa-pencil', 'ActivationCodeController.Edit');
